#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -x

version="v$(cat version/version )"
release_version="v$(cat version/version | cut -d - -f 1)"
arch=linux.x86-64

echo Building lifecycle binaries
echo RC Version "$version"
echo Release Version "$release_version"

pushd lifecycle-repo
    LIFECYCLE_VERSION="$release_version" make build
    LIFECYCLE_VERSION="$release_version" make package

    # Note: We're renaming to the RC version during the move, so the archive can be easily promoted
    mv out/"lifecycle-$release_version+$arch.tgz" ../built-lifecycle/"lifecycle-$version+$arch.tgz"
popd

echo Built
ls -al built-lifecycle/

echo Archive SHAs:
  sha256sum "built-lifecycle/lifecycle-$version+$arch.tgz"
  sha512sum "built-lifecycle/lifecycle-$version+$arch.tgz"

echo DONE
