#!/usr/bin/env bash

source ci/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail
set -x

version="$(cat version/version )"
release_version="$(cat version/version | cut -d - -f 1)"

echo Building lifecycle binaries
echo RC Version "$version"
echo Release Version "$release_version"

pushd lifecycle-repo
    SCM_REPO=https://github.com/buildpacks/lifecycle LIFECYCLE_VERSION="$release_version" make build
    SCM_REPO=https://github.com/buildpacks/lifecycle LIFECYCLE_VERSION="$release_version" make package

    # Note: We're renaming to the RC version during the move, so the archive can be easily promoted
    mv out/"lifecycle-v$release_version+linux.x86-64.tgz" ../built-lifecycle/"lifecycle-v$version+linux.x86-64.tgz"
    mv out/"lifecycle-v$release_version+windows.x86-64.tgz" ../built-lifecycle/"lifecycle-v$version+windows.x86-64.tgz"
popd

echo Built
ls -al built-lifecycle/

echo Archive SHAs:
  sha256sum "built-lifecycle/lifecycle-v$version+linux.x86-64.tgz"
  sha512sum "built-lifecycle/lifecycle-v$version+windows.x86-64.tgz"

echo DONE
