#!/usr/bin/env bash

source ci/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail

set -x
version="$(cat lifecycle-version/version)-$(cat lifecycle-build-number/version | cut -d "-" -f2)"

./lifecycle-repo/images/bin/build -v $version

echo $version >> ./calculated-lifecycle-version/version

for image in base run build samples; do
  docker tag "packs/$image:$version" "packs/$image:dev"
  docker save "packs/$image:dev" -o "built-lifecycle-images/$image.tar"
done
