#!/usr/bin/env bash

source /opt/resource/common.sh
start_docker 3 3

set -o errexit
set -o nounset
set -o pipefail

function waitForContainer() {
    container_id=$1
    health=$(docker container inspect $container_id --format "{{.State.Health.Status}}")
    if [[ $health == "healthy" ]]; then
      echo container status: "$health"
      return
    else
      echo container status: "$health"
    fi
    sleep 3
    waitForContainer "$container_id"
}

chmod +x ./pack-linux-binary/pack-*-linux

echo "pack create-builder "cnbs/samples:dev" -b ./samples-repo/builder.toml"
./pack-linux-binary/pack-*-linux create-builder "cnbs/samples:dev" -b ./samples-repo/builder.toml

echo "saving "cnbs/samples:dev" to samples-tar"
docker save cnbs/samples:dev -o ./samples-tar/samples.tar

echo "pack build --builder "cnbs/samples:dev" -p ./sample-java-app cnbs/sample-java-app"
./pack-linux-binary/pack-*-linux build --builder "cnbs/samples:dev" -p ./sample-java-app cnbs/sample-java-app

echo "docker run -d --rm -p 8080:8080 cnbs/sample-java-app"
container_id=$(docker run -d --rm -p 8080:8080 cnbs/sample-java-app)
trap "docker kill $container_id" EXIT

apk update
apk add curl

waitForContainer "$container_id"

echo "curling localhost:8080"
curl -o /dev/null --fail localhost:8080