#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

set -x

jq_version=1.6

wget "https://github.com/stedolan/jq/releases/download/jq-${jq_version}/jq-linux64" \
 -O /usr/local/bin/jq \
 && chmod +x /usr/local/bin/jq

cd lifecycle-repo
make test
