#!/usr/bin/env bash

source ci/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail

set -x

docker load -i golang-image/image
docker tag "$(cat golang-image/image-id)" "golang"

cd lifecycle-repo

docker_run golang make test
