#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo Moving binaries

pushd lifecycle-binaries
 tar xzf ../lifecycle/lifecycle-*.tgz --strip-components 1
popd

echo lifecycle-binaries after moves:

ls -al lifecycle-binaries

echo Done.
