#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail


export GO111MODULE=on
export GOOS=linux
export GOARCH=amd64
export CGO_ENABLED=0

version="$(cat lifecycle-version/version)-$(cat lifecycle-build-number/version | cut -d "-" -f2)"

echo Building lifecycle binaries
echo Version "$version"

pushd ./lifecycle-repo
  go build -mod=vendor -o "../lifecycle-binaries/detector-$version-$GOOS"  -a ./cmd/detector/main.go
  go build -mod=vendor -o "../lifecycle-binaries/analyzer-$version-$GOOS"  -a ./cmd/analyzer/main.go
  go build -mod=vendor -o "../lifecycle-binaries/builder-$version-$GOOS"   -a ./cmd/builder/main.go
  go build -mod=vendor -o "../lifecycle-binaries/exporter-$version-$GOOS"  -a ./cmd/exporter/main.go
  go build -mod=vendor -o "../lifecycle-binaries/launcher-$version-$GOOS"  -a ./cmd/launcher/main.go
popd


echo Built:

ls -al lifecycle-binaries/

echo Done.
