#! /usr/bin/env sh

version="$(cat version/version)"
outputs_dir="$PWD/release-artifacts"

apk add zip

echo "pack v$version" > "$outputs_dir/name"
echo "v$version" > "$outputs_dir/tag"
git -C pack-repo rev-parse HEAD > "$outputs_dir/commit-sha"

# linux
mv pack-linux-binary/pack* pack-linux-binary/pack
chmod +x pack-linux-binary/pack
tar czf "$outputs_dir/pack-v$version-linux.tgz" pack -C pack-linux-binary/

# macos
mv pack-darwin-binary/pack* pack-darwin-binary/pack
chmod +x pack-darwin-binary/pack
tar czf "$outputs_dir/pack-v$version-macos.tgz" pack -C pack-darwin-binary/

# windows
mv pack-windows-binary/pack-* pack-windows-binary/pack.exe
cd pack-windows-binary
zip pack.zip pack.exe
cd ..
mv pack-windows-binary/pack.zip "$outputs_dir/pack-v$version-windows.zip"