#! /usr/bin/env sh

version="$(cat lifecycle-version/version)"
outputs_dir="$PWD/release-artifacts"

echo "lifecycle v$version" > "$outputs_dir/name"
echo "v$version" > "$outputs_dir/tag"
git -C lifecycle-repo rev-parse HEAD > "$outputs_dir/commit-sha"
mv lifecycle-linux/lifecycle-*.tgz "$outputs_dir/lifecycle-v$version+linux.x86-64.tgz"
mv lifecycle-windows/lifecycle-*.tgz "$outputs_dir/lifecycle-v$version+windows.x86-64.tgz"