#!/usr/bin/env bash

source ci/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail

set -x

cd pack-repo

echo "registry:2 image is needed for pack unit tests"
docker pull registry:2

IS_CI=true go test -mod=vendor -v -count=1 -parallel=1 -timeout=0 ./...
