#!/usr/bin/env bash

source ci/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail

set -x

docker load -i golang-image/image
docker tag "$(cat golang-image/image-id)" "golang"

cd pack-repo

docker_run golang go test -mod=vendor -v -count=1 -parallel=1 -timeout=0 ./...
