#!/usr/bin/env sh

set -o errexit
set -o nounset
set -o pipefail

# Extract the pack binary
tar xzf ./pack-github-release/pack-*-linux.tgz -C ./pack-linux-binary/
mv pack-linux-binary/pack pack-linux-binary/pack-bin-linux # Rename for acceptance tests

# Extract the pack source to get acceptance test for that release
if [ $GET_SOURCE == "true" ]; then
    tar xzf ./pack-github-release/source.tar.gz -C ./pack-repo --strip-components=1

    # FIXME: remove this after releasing v0.3.0
    sed -i 's/lifecycleVersion == "0\.2\.0"/lifecycleVersion >= "0\.2\.0"/' ./pack-repo/acceptance/acceptance_test.go
fi
