#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

## TODO: replace this task with input mapping

set -x
release_version="$(cat lifecycle-version/version)"

echo $release_version > ./release-lifecycle-version/version


