#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo Calculating version

version=$(cat lifecycle-version/version)
marketing_version=3.0.0-alpha${version:3}

echo Version is: $marketing_version
echo Writing out version

echo $marketing_version >> ./calculated-lifecycle-version/version

echo Done.