#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo Calculating version

version="$(cat lifecycle-version/version)-$(cat lifecycle-build-number/version | cut -d "-" -f2)"

echo Version is: $version
echo Writing out version

echo $version >> ./calculated-lifecycle-version/version

echo Done.