#!/usr/bin/env bash

source ci/scripts/common.sh

set -o errexit
set -o nounset
set -o pipefail

set -x

docker load -i packs-samples-image/image
docker tag "$(cat packs-samples-image/image-id)" "packs/samples:dev"

docker load -i packs-build-image/image
docker tag "$(cat packs-build-image/image-id)" "packs/build:dev"

docker load -i packs-run-image/image
docker tag "$(cat packs-run-image/image-id)" "packs/run:dev"

mv pack-linux-binary/pack-*-linux pack-linux-binary/pack
pack_path=$PWD/pack-linux-binary/pack
chmod +x ${pack_path}

cd pack-repo
docker_run -e "PACK_TAG=dev" -e "PACK_PATH=/tmp/pack" -v "$pack_path":/tmp/pack golang go test -mod=vendor -tags=acceptance -v -count=1 -parallel=1 -timeout=0 ./acceptance
