#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo Generating docker build args

version=$(cat version/version)

cat << EOF > docker-build-args/args.json
  {
    "base_image":   "gcr.io:443/cncf-buildpacks-ci/packs/base:${version}"
  }
EOF

echo Generated JSON:

cat docker-build-args/args.json

echo Done.
