#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

pack_version=$(cat pack-version/version)
pack_base_version=$(cat pack-version/version | cut -d "-" -f1)
export PACK_PATH="$PWD/pack-release/pack-${pack_version}-${OS_NAME}"
export GOOS=${OS_NAME}

echo Building 'pack' CLI version: $pack_version

pushd pack-repo
    version_string="v$pack_base_version (git sha: $(git log -1 --pretty=%H))"
    CGO_ENABLED=0 go build -mod=vendor -ldflags "-X 'main.Version=${version_string}'" -o "$PACK_PATH" ./cmd/pack
popd

echo "pack v${pack_version}" > pack-release/pack-release-name

echo Built:

ls -al pack-release/

echo Done.
