#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

version=$(cat version/version)
base_version=$(cat version/version | cut -d "-" -f1)
export PACK_PATH="$PWD/pack-release/pack-${version}-${GOOS}"

echo Building 'pack' CLI version: $version

pushd pack-repo
    version_string="v$base_version (git sha: $(git log -1 --pretty=%H))"
    PACK_CI=true PACK_VERSION=${version_string} make build
    mv ./out/pack "$PACK_PATH"
popd

echo "pack v${version}" > pack-release/pack-release-name

echo Built:

ls -al pack-release/

echo Done.
